// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AckStatus } from "./AckStatus";

/**
 * Bidirectional messages (can be sent by either side)
 */
export type Ack = { messageId: string, status: AckStatus, };
