// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledgment for WS-ACP events with last processed sequence.
 */
export type AcpAck = { 
/**
 * The worktree ID
 */
worktreeId: string, 
/**
 * The ACP session ID
 */
acpSessionId: string, 
/**
 * The last sequence number successfully processed
 */
lastSequence: bigint, };
