// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ACP error codes for programmatic handling.
 */
export type AcpErrorCode = "AgentCrash" | "InitFailed" | "SessionNotFound" | "PromptFailed" | "ToolFailed" | "CancelFailed" | "Timeout" | "InvalidRequest" | "Internal";
