// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpErrorCode } from "./AcpErrorCode";

/**
 * Structured error from ACP bridge.
 */
export type AcpError = { 
/**
 * The worktree ID (if applicable)
 */
worktreeId: string, 
/**
 * The ACP session ID (if applicable)
 */
acpSessionId: string | null, 
/**
 * Error code for programmatic handling
 */
code: AcpErrorCode, 
/**
 * Human-readable error message
 */
message: string, 
/**
 * Additional details (JSON string)
 */
details: string | null, 
/**
 * Whether this error is recoverable
 */
recoverable: boolean, };
