// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpContextUpdate } from "./AcpContextUpdate";
import type { AcpError } from "./AcpError";
import type { AcpPromptChunk } from "./AcpPromptChunk";
import type { AcpPromptComplete } from "./AcpPromptComplete";
import type { AcpResumeMarker } from "./AcpResumeMarker";
import type { AcpSessionInit } from "./AcpSessionInit";
import type { AcpSessionStatusEvent } from "./AcpSessionStatusEvent";
import type { AcpToolUseEvent } from "./AcpToolUseEvent";

/**
 * WS-ACP event types - stateless vocabulary for ACP bridge communication.
 */
export type AcpEvent = { "eventType": "SessionInit", "data": AcpSessionInit } | { "eventType": "SessionStatus", "data": AcpSessionStatusEvent } | { "eventType": "PromptChunk", "data": AcpPromptChunk } | { "eventType": "PromptComplete", "data": AcpPromptComplete } | { "eventType": "ToolUse", "data": AcpToolUseEvent } | { "eventType": "ContextUpdate", "data": AcpContextUpdate } | { "eventType": "Error", "data": AcpError } | { "eventType": "ResumeMarker", "data": AcpResumeMarker };
