// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpChunkContent } from "./AcpChunkContent";

/**
 * Streaming prompt response chunk.
 */
export type AcpPromptChunk = { 
/**
 * The worktree ID
 */
worktreeId: string, 
/**
 * The ACP session ID
 */
acpSessionId: string, 
/**
 * Chunk content (text or structured data)
 */
content: AcpChunkContent, 
/**
 * True if this is the final chunk for this content item
 */
isFinal: boolean, };
