// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";

export type AgentStatusUpdate = { id: string, worktreeId: string, agentType: string, status: AgentStatus, startedAt: number, };
