// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSessionData } from "./AgentSessionData";
import type { SettingData } from "./SettingData";
import type { TerminalSessionData } from "./TerminalSessionData";
import type { WorkspaceData } from "./WorkspaceData";
import type { WorktreeData } from "./WorktreeData";

export type StateSnapshot = { requestId: string, workspaces: Array<WorkspaceData>, worktrees: Array<WorktreeData>, agentSessions: Array<AgentSessionData>, terminalSessions: Array<TerminalSessionData>, settings: Array<SettingData>, };
