// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSessionData = { id: string, worktreeId: string, label: string | null, shell: string, createdAt: bigint, };
