// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeData = { id: string, workspaceId: string, branchName: string, path: string, status: string, createdAt: bigint, };
