// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceData = { id: string, name: string, rootPath: string, color: string | null, icon: string | null, worktreeBaseDir: string | null, settings: string | null, createdAt: bigint, updatedAt: bigint, };
